object frmWhats: TfrmWhats
  Left = 0
  Top = 0
  Align = alTop
  Caption = 'frmWhats'
  ClientHeight = 216
  ClientWidth = 581
  Color = clBtnFace
  DockSite = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = False
  PopupMode = pmAuto
  PixelsPerInch = 96
  TextHeight = 13
end
