// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Teste;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {RCFileType} {Teste_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Teste_DRC.res' 'Teste_DRC.rc'}

{$E ENU}

begin
end.
