// Do not edit. This file is machine generated by the Resource DLL Wizard.

library LicenseMSoftArena;

{ITE} {DFMFileType} {TLockApplication\CadastroUnt.dfm}
{ITE} {DFMFileType} {TLockApplication\LockApplicationEmailStatus.dfm}
{ITE} {DFMFileType} {TLockApplication\LockApplicationInterface.dfm}
{ITE} {DFMFileType} {TLockApplication\unSecDados.dfm}
{ITE} {RCFileType} {C\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\LicenseMSoftArena_DRC.rc}

{$R 'TLockApplication\CadastroUnt.dfm' 'cadastro:TForm'}
{$R 'TLockApplication\LockApplicationEmailStatus.dfm' 'StatusEmail:TForm'}
{$R 'TLockApplication\LockApplicationInterface.dfm' 'Bloqueio:TForm'}
{$R 'TLockApplication\unSecDados.dfm' 'dmSecDados:TDataModule'}
{$R 'C\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\LicenseMSoftArena_DRC.res' 'C\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\LicenseMSoftArena_DRC.rc'}

{$E ESN}

begin
end.
